.TH sgsc(1) WCS "15 November 1996"
.SH Name
sgsc \- Find HST GSC stars in a square on the sky
.SH Synopsis
sgsc [options] [-b or -j] ra dec
.SH Description
.I sgsc
is a utility for finding all of the Hubble Space Telescope Guide Star
Catalog objects in a specified region of the sky and listing their sky
positions.  Output is to standard out, unless the -w flag is set, in
which case it goes to objectname.gsc or search.gsc. It is somewhat
similar to RGSC, which can search from lists of coordinates but cannot
sort the output. 
.SH Options
.B \-1
List single closest catalog source
.B \-b <RA> <Dec>
Output B1950 (FK4) coordinates
.B \-d
Sort by distance from center instead of flux
.B \-g <class>
Object class (0=stars 3=galaxies -1=all)
.B \-h
print heading, else do not 
.B \-j <RA> <Dec>
Output J2000 (FK5) coordinates around this center
.B \-m <magnitude>
Faint magnitude limit
.B \-n <num>
Number of brightest stars to print 
.B \-o <name>
Object name used for output file naming
.B \-r <radius>
Radius of search circle 1in arcsec (default 10)
.B \-s
Sort by RA instead of flux 
.B \-t
Tab table to standard output as well as file
.B \-v
Verbose listing of processing intermediate results
.B \-w
Write tab table output file imagename.gsc
.SH See Also
rgsc(1), suac(1), scat(1)
.SH Author
Doug Mink, SAO (dmink@cfa.harvard.edu)
