.TH imfilt(1) WCSTools "18 April 2006"
.SH Name
imfilt \- Smooth FITS and IRAF image files
.SH Synopsis
imfilt [options] Fits or IRAF file(s)
.SH Description
.I imfilt
is a utility for smoothing FITS or IRAF images.  Values are computed from
pixels in rectangular boxes centered on and replacing each pixel in an
image.  The options are mean, median, or a Gaussian weighting.  IRAF files
may be written out as FITS files.
.SH Options
.B \-a dx dy
Mean filter dx x dy pixels
.B \-f factor
Reduce each image dimension by this factor
.B \-g dx
Gaussian filter dx pixels square
.B \-h halfwidth
Gaussian half-width at half-height
.B \-l num
Logging interval in lines
.B \-m dx dy
Median filter dx x dy pixels
.B \-o [filename]
If no argument, overwrite input image, else write the output to filename.
.B \-v
Verbose

.SH Author
Doug Mink, SAO (dmink@cfa.harvard.edu)
